# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1e6f016e2dee4780f251141a83017f4f2ddb6445c4b283553953d7d5b51423be104b17b49287e7e082aa457e3d8fed30af00c5fb5ae76c900c097ef76331a7e

test:
  secret_key_base: 66031e2cc254a1c56c8210b2177b808436e12aba660f9e5919cd93b84fd2ec3ab092d730941dc393e27130bb344eebad8abed19ed7affb8af3e042b811d9f9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
